apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-deployment
  namespace: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processing
  template:
    metadata:
      labels:
        app: image-processing
    spec:
      containers:
        - name: image-processing
          image: appregister.azurecr.io/image-processing
          imagePullPolicy: Always
          resources:
            limits:
              memory: "8Gi"
              cpu: "4"
            requests:
              memory: "4Gi"
              cpu: "2"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
