name: Deploy to AKS

on:
  push:
    branches:
      - master
    paths:
      - "k8s/dev/image-process/deploy.yaml"
      - "image-process/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}/image-processing:${{ github.sha }} ./image-process
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}/image-processing:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP_DEV }}
          cluster-name: ${{ secrets.AZURE_AKS_NAME_DEV }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: image
          name: ${{ secrets.AZURE_AKS_NAME }}
          resource_group: ${{ secrets.AZURE_RESOURCE_GRP }}
          manifests: |
            k8s/dev/image-process/deploy.yaml
          images: |
            ${{ secrets.AZURE_REGISTRY_NAME }}/image-process:${{ github.sha }}
          kubectl-version: '1.22.0'
